import { ALL_CUSTOMERS_ENDPOINT_FE, EXPENDITURE_ANALYTICS_ENDPOINT_FE, EXPENDITURE_LIST_ENDPOINT_FE, HOME_ENDPOINT_FE, MARGIN_ANALYTICS_ENDPOINT_FE, MONTH_PAYMENTS_ENDPOINT_FE, ORDERS_LISTING_ENDPOINT_FE, PAYMENTS_ANALYTICS_ENDPOINT_FE, STOCKS_LIST_ENDPOINT_FE } from "./endpoints"

// Main buttons
export const SIDEBAR_MANAGE_STOCK = "manage_stock"
export const SIDEBAR_CUSTOMERS = "customers"
export const SIDEBAR_EXPENDITURE = "expenditure"
export const SIDEBAR_ANALYTICS = "analytics"
export const SIDEBAR_PAYMENTS = "payments"
export const SIDEBAR_ORDERS = "orders"


// Sub Menu Options
export const SIDEBAR_DASHBOARD = "dashboard"
export const SIDEBAR_ADD_STOCK = "add_stock"
export const SIDEBAR_STOCKS_LIST = "stocks_list"
export const SIDEBAR_MONTH_PAYMENTS = "month_payments"
export const SIDEBAR_CUSTOMER_LIST = "customers_list"
export const SIDEBAR_EXPENDITURE_LIST = "expenditure_list"
export const SIDEBAR_EXPENDITURE_ANALYTICS = "expenditure_analytics"
export const SIDEBAR_PAYMENTS_ANALYTICS = "payments_analytics"
export const SIDEBAR_MARGIN_ANALYTICS = "margin_analytics"
export const SIDEBAR_ORDERS_LIST = "orders_list"

//
type SUB_MENU_NAVIGATION_MAPPING_PROPS = {
    [key: string]: string
}

export const SUB_MENU_NAVIGATION_MAPPING: SUB_MENU_NAVIGATION_MAPPING_PROPS = {
    [SIDEBAR_STOCKS_LIST]: STOCKS_LIST_ENDPOINT_FE,
    [SIDEBAR_DASHBOARD]: HOME_ENDPOINT_FE,
    [SIDEBAR_MONTH_PAYMENTS]: MONTH_PAYMENTS_ENDPOINT_FE,
    [SIDEBAR_CUSTOMER_LIST]: ALL_CUSTOMERS_ENDPOINT_FE,
    [SIDEBAR_EXPENDITURE_LIST]: EXPENDITURE_LIST_ENDPOINT_FE,
    [SIDEBAR_EXPENDITURE_ANALYTICS]: EXPENDITURE_ANALYTICS_ENDPOINT_FE,
    [SIDEBAR_PAYMENTS_ANALYTICS]: PAYMENTS_ANALYTICS_ENDPOINT_FE,
    [SIDEBAR_MARGIN_ANALYTICS]: MARGIN_ANALYTICS_ENDPOINT_FE,
    [SIDEBAR_ORDERS_LIST]: ORDERS_LISTING_ENDPOINT_FE
}


// Global CSS
export const pageHeadingStyle = { margin: 0, alignSelf: "center", color: "white" }
